apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris-hpa
  namespace: ml-system
  labels:
    app: iris
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
