apiVersion: v1
kind: ConfigMap
metadata:
  name: vegeta-config
  namespace: ml-system
data:
  get-target: "GET http://iris.ml-system.svc.cluster.local:8000/predict/test"
  post-target: "POST http://iris.ml-system.svc.cluster.local:8000/predict\nContent-Type: application/json\n@/opt/data.json"
