apiVersion: v1
kind: Pod
metadata:
  name: vegeta
  namespace: ml-system
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                  - "true"
  containers:
    - name: vegeta
      image: shibui/ml-system-in-actions:load_test_pattern_client_0.0.1
      imagePullPolicy: Always
      command:
        - tail
        - -f
        - /dev/null
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 1Gi
      volumeMounts:
        - name: vegeta
          mountPath: "/opt/vegeta"
          readOnly: true
  volumes:
    - name: vegeta
      configMap:
        name: vegeta-config
