apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ml-system-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - path: ml-system
          - path: namespaces
          - path: argocd
  template:
    metadata:
      name: "{{path}}" # generatorsで生成した"path"パラメータを使用
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/aya-se/ml-system-k8s.git
        targetRevision: HEAD
        path: "manifests/{{path}}" # generatorsで生成した"path"パラメータを使用
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path}}" # generatorsで生成した"path"パラメータを使用
      syncPolicy:
        automated: {}
