apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - path: istio-base
            chart: base
          - path: istiod
            chart: istiod
  template:
    metadata:
      name: "{{path}}" # generatorsで生成した"path"パラメータを使用
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: "{{chart}}" # generatorsで生成した"chart"パラメータを使用
        targetRevision: 1.22.0
        helm:
          releaseName: "{{path}}" # generatorsで生成した"path"パラメータを使用
      destination:
        server: https://kubernetes.default.svc
        namespace: istio-system
      syncPolicy:
        automated: {}
