apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  namespace: iris
  labels:
    app: iris
spec:
  # selector：Deploymentが管理するPodを特定するためのセレクタ
  selector:
    matchLabels:
      app: iris
  # template：Deploymentが管理するPodの設定
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
        - name: iris
          image: shibui/ml-system-in-actions:model_in_image_pattern_0.0.1 # コンテナのイメージ
          imagePullPolicy: Always # イメージの取得方法
          ports:
            - containerPort: 8000 # ポート番号
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iris
  namespace: iris
  labels:
    app: iris
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
