apiVersion: v1
kind: Service
metadata:
  name: iris
  namespace: iris
spec:
  selector:
    app: iris
  # ports: Serviceが公開するポート
  ports:
    - protocol: TCP
      port: 8000 # Serviceのポート
      targetPort: 8000 # Podのポート
  type: LoadBalancer # Serviceのタイプ
